version: '3.9'

networks:
  serverless-localstack-plugin-example:
    name: serverless-localstack-plugin-example-network

services:
  aws:
    container_name: serverless-localstack-plugin-example-aws
    image: localstack/localstack:1.4.0
    ports:
      - 4566:4566
    environment:
      - EDGE_PORT=4566
      - DISABLE_CORS_CHECKS=1
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=0
    volumes:
      - $PWD:$PWD
    networks:
      - serverless-localstack-plugin-example
