service: serverless-localstack-plugin-example
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-localstack
  - serverless-offline

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    keepOutputDirectory: true
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autoStart: true
    debug: true
    lambda:
      mountCode: true
    docker:
      sudo: false

provider:
  name: aws
  memorySize: 128
  runtime: nodejs14.x

functions:
  first:
    handler: first.hello
    events:
      - http:
          method: GET
          path: /first
